In [9]:
from sklearn import svm, datasets
import pandas as pd
import numpy  as np
from sklearn.model_selection import GridSearchCV

#ML
from sklearn.neighbors import KNeighborsClassifier

#import libraries for model validation
from sklearn.model_selection import LeaveOneOut
from sklearn.model_selection import LeavePOut
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.model_selection import RepeatedKFold
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.model_selection import cross_val_score

In [35]:
# load the training data from iris.txt
df_training = pd.read_csv('iris.csv', delim_whitespace=True)

In [36]:
iris = df_training
iris = datasets.load_iris()

In [37]:
iris.data[:3]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2]])

In [38]:
iris.target[:3]

array([0, 0, 0])

In [39]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [40]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [41]:
x = iris.data
y = iris.target

In [43]:
#instantiate the KNN classifer
#{'metric': 'minkowksi', 'n_neighbors': 5, 'p':2, 'weights': 'uniform'}
clf = KNeighborsClassifier()

In [44]:
#Get the KNN parameters
clf.get_params()

{'algorithm': 'auto',
 'leaf_size': 30,
 'metric': 'minkowski',
 'metric_params': None,
 'n_jobs': None,
 'n_neighbors': 5,
 'p': 2,
 'weights': 'uniform'}

In [45]:
#Get KNN parameter keys
clf.get_params().keys()
#Returns a dictionary and this will help you set range values.

dict_keys(['algorithm', 'leaf_size', 'metric', 'metric_params', 'n_jobs', 'n_neighbors', 'p', 'weights'])

In [52]:
n_neighbors = [3,5,7,9,11,13,15,19,23,29]
algos = ['ball_tree', 'kd_tree']
dist_metric = ['minkowksi']
p_root = [1,2,3,4,5]
weights = ['uniform', 'distance']
leaf_size = [15,30,40,50,60,70]

In [79]:
#Define the parameters dict
parameters = dict(
                n_neighbors = n_neighbors,
                #algorithm = algos,
                metric = dist_metric,
                p = p_root,
                weights = weights,
                #Leaf_size = leaf_size
              )

print(parameters)

{'n_neighbors': [3, 5, 7, 9, 11, 13, 15, 19, 23, 29], 'metric': ['minkowksi'], 'p': [1, 2, 3, 4, 5], 'weights': ['uniform', 'distance']}


In [80]:
# define splits 
n_splits = 5

kf = KFold(n_splits = n_splits, shuffle=True, random_state=100)
#skf = StratifiedKFold(n_splits = n_splits, shuffle=True, random_state=100)

In [81]:
#Instantiate the grid search CV - a for loop
grid = GridSearchCV(estimator = clf,
                    param_grid = parameters,
                    scoring = 'accuracy', 
                    cv=kf,
                    verbose=2)


In [82]:
#fit the data to the grid object 
grid.fit(x,y)

Fitting 5 folds for each of 100 candidates, totalling 500 fits
[CV] END metric=minkowksi, n_neighbors=3, p=1, weights=uniform; total time=   0.0s
[CV] END metric=minkowksi, n_neighbors=3, p=1, weights=uniform; total time=   0.0s
[CV] END metric=minkowksi, n_neighbors=3, p=1, weights=uniform; total time=   0.0s
[CV] END metric=minkowksi, n_neighbors=3, p=1, weights=uniform; total time=   0.0s
[CV] END metric=minkowksi, n_neighbors=3, p=1, weights=uniform; total time=   0.0s
[CV] END metric=minkowksi, n_neighbors=3, p=1, weights=distance; total time=   0.0s
[CV] END metric=minkowksi, n_neighbors=3, p=1, weights=distance; total time=   0.0s
[CV] END metric=minkowksi, n_neighbors=3, p=1, weights=distance; total time=   0.0s
[CV] END metric=minkowksi, n_neighbors=3, p=1, weights=distance; total time=   0.0s
[CV] END metric=minkowksi, n_neighbors=3, p=1, weights=distance; total time=   0.0s
[CV] END metric=minkowksi, n_neighbors=3, p=2, weights=uniform; total time=   0.0s
[CV] END metric=min

/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:372: FitFailedWarning: 
500 fits failed out of a total of 500.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
500 fits failed with the following error:
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/opt/anaconda3/lib/python3.9/site-packages/sklearn/neighbors/_classification.py", line 198, in fit
    return self._fit(X, y)
  File "/opt/anaconda3/lib/python3.9/site-packages/sklearn/neighbors/_base.py", line 437, in _fit
    self._check_algorithm_metric()
  File "/opt/anaconda3/lib/python3.9/sit

ValueError: Metric 'minkowksi' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.

In [85]:
#What are the best parameters that you got?
print('Estimator: \n',   grid.best_estimator_)
print('Best params : \n', grid.best_params_)
print(grid.classes_)
print(grid.best_score_)

Estimator: 
 KNeighborsClassifier(metric='minkowksi', n_neighbors=3, p=1)
Best params : 
 {'metric': 'minkowksi', 'n_neighbors': 3, 'p': 1, 'weights': 'uniform'}
[0 1 2]
nan
